## Provisioning options

Every provisioning action (such as `provision`, `install`, `uninstall`, etc) may accept provisioning options. Provisioning options may control various things, e.g. enable debug mode in one of the product-specific provisioning plugins, activate a certain provisioning mode, etc.

### Persistent and non-persistent options

Provisioning options can be persistent and non-persistent.

*Persistent options* are persisted in the provisioning configuration file when the provisioning process has succesfully finished. E.g. if `prod1` is installed with `option1`, the provisioned configuration will look like this
[source,xml]
----
<installation xmlns="urn:jboss:galleon:provisioning:2.0">
    <feature-pack location="prod1@maven(org.jboss.universe:community-universe):1#1.0.0.Final"/>
    <options>
        <option name="option1" value="true"/>
    </options>
</installation>
----

Now if the user installs `prod2`, `option1` will still be effective during re-provisioning and the config will change to
[source,xml]
----
<installation xmlns="urn:jboss:galleon:provisioning:2.0">
    <feature-pack location="prod1@maven(org.jboss.universe:community-universe):1#1.0.0.Final"/>
    <feature-pack location="prod2@maven(org.jboss.universe:community-universe):1#1.0.0.Final"/>
    <options>
        <option name="option1" value="true"/>
    </options>
</installation>
----

NOTE: Option values are not necessarily `true` or `false`, they may have various values. The only restriction is they *must* have some value.

*Non-persistent* options, on the other hand, are not automatically stored in the provisioning configuration. They are used only for the provisioning action they were specified for.

### Built-in and product-specific options

Provisioning options can be provided by the core provisioning mechanism itself and the product-specific provisioning plugins.

#### Built-in provisioning options

.Built-in provisioning options
|===
|Name |Purpose |Value set
|config-stability-level |<<_stability_level,Stability level for configs>>. 
This stability level is used to enable the stability level of all features present in the generated configurations. 
By default the configs stability level set in the feature-pack is used.| `default`, `community`, `preview`, `experimental`
|export-system-paths |<<_protected_system_files,Store the system paths declared by Feature Packs in .galleon/systempaths.txt>> | `false` _(default)_, `true`
|ignore-not-excluded-layers |<<_excluding_layers_from_configuration_models,Suppresses the error when layers configured to be excluded would not have otherwise been installed>> |`false` _(default)_, `true`
|optional-packages |<<_feature_pack_original_effective_package_set,Optional package dependencies inclusion policy>> |`all` _(default)_, `none`, `passive`, `passive+`
|package-stability-level |<<_stability_level,Stability level for packages>>. This stability level is used to set the stability level of all provisioned packages.
By default the packages stability level set in the feature-pack is used.| `default`, `community`, `preview`, `experimental`
|stability-level |<<_stability_level,Stability level for both configs and packages>>. This option is a convenience 
allowing to set both the config and package stability level using a single option. It can't be set when `config-stability-level` or `package-stability-level` are set| `default`, `community`, `preview`, `experimental`

|store-input-provisioning-config |<<_storing_input_provisioning_config,Store the provisioning config received as input in the generated .galleon/provisioning.xml file>> |`false` _(default)_, `true`
|version-convergence |<<_dependency_version_convergence,Disables or enables the dependency version convergence>> | `first-processed` _(default)_, `fail`
|===

#### Product provisioning options

Product-specific provisioning options are exposed by the product-specific provisioning plugins attached to the feature-packs.
