include::../../../maven-plugins/target/generated-sources/plugin/provision-mojo.adoc[]

.Feature-pack parameters
[%autowidth.stretch]
|===
|Name |Required |Default value |Description
|groupId |yes |- |Feature-pack Maven artifact groupId.
|artifactId |yes |- |Feature-pack Maven artifactId.
|version |no |- |Feature-pack artifact version (if not specified the feature-pack must be a transitive dependency of a feature-pack with the version specified.
|inherit-configs |no |true |Whether to inherit the default feature-pack configs
|included-configs |no |- |Default feature-pack configs that should be included.
|excluded-configs |no |- |Default feature-pack configs that should be excluded.
|inherit-packages |no |true |Whether to inherit the default feature-pack packages.
|included-packages |no |- |Default feature-pack packages that should be included.
|excluded-packages |no |- |Default feature-pack packages that should be excluded.
|===

Example
[source,xml]
----
<plugin>
    <groupId>org.jboss.galleon</groupId>
    <artifactId>galleon-maven-plugins</artifactId>
    <executions>
        <execution>
            <goals>
                <goal>provision</goal>
            </goals>
            <configuration>
                <install-dir>${project.build.directory}/${project.build.finalName}</install-dir>
                <feature-packs>
                    <feature-pack>
                        <groupId>org.wildfly.core</groupId>
                        <artifactId>wildfly-core-galleon-pack</artifactId>
                        <inherit-configs>false</inherit-configs>
                        <excluded-packages>
                            <name>product.conf</name>
                            <name>docs.schema</name>
                        </excluded-packages>
                    </feature-pack>
                    <feature-pack>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>wildfly-servlet-galleon-pack</artifactId>
                        <version>${project.version}</version>
                            <excluded-packages>
                            <name>product.conf</name>
                            <name>docs.schema</name>
                        </excluded-packages>
                    </feature-pack>
                </feature-packs>
                <plugin-options>
                    <jboss-maven-dist/>
                </plugin-options>
            </configuration>
        </execution>
    </executions>
</plugin>
----

