### Configuration dependencies

When all the configuration models have been resolved by the provisioning mechanism, the plugins attached to the installed feature-packs are invoked to generate the final configuration files. The plugins will see the resolved configs as a list. Certain configuration models though may depend on other configuration models being generated first. To eliminate the trouble of ordering the configs according to their dependencies, config dependencies can be expressed in `config` elements. E.g.

[source,xml]
----
    <config model="host">
        <config-deps>
            <config-dep id="domain-dep" model="domain"/>
        </config-deps>
    </config>
----

In the example above all the configs of model *host* will appear in the resolved config list after all the *domain* model configs. `config-dep` `id` is used to identify the config dependencies when the config models are merged.

The example above illustrates only model dependencies. But `config-dep` may also include `name` attribute.
