### Configuration dependencies

When all the configuration models have been resolved by the provisioning mechanism, the plugins attached to the installed feature-packs are invoked to generate the final configuration files. The plugins will see the resolved configurations as a list. Certain configuration models though may depend on other configuration models being generated first. To eliminate the trouble of ordering the configurations according to their dependencies in the plugins, configuration dependencies can be expressed in `config` elements. E.g.

[source,xml]
----
    <config model="host">
        <config-deps>
            <config-dep id="domain-dep" model="domain"/>
        </config-deps>
    </config>
----

In the example above all the configurations of model `host` will appear in the resolved config list after all the configurations of model `domain`. `config-dep` `id` is used to identify the configuration dependencies when the configuration models are merged.

The example above illustrates a dependency on a configuration model. But `config-dep` may also include `name` attribute.
