### Excluding default configs from the installation

The simplest way to exclude configs from the installation is

[source,xml]
----
<installation xmlns="urn:jboss:galleon:provisioning:1.0">
    <feature-pack location="fp1@maven(org.jboss.universe:community-universe):1#1.0.0.Final">

        <default-configs inherit="false"/>

    </feature-pack>
</installation>
----

`inherit="false"` attribute indicates that none of the configs should be included into the distribution by default. If the attribute is not present, its value is assumed to be `true`.

NOTE: `feature-pack` element in the example above could as well appear under `dependecies` element of `feature-pack.xml`. Meaning the XML type of these elements are equivalent - they both describe a customized feature-pack. The examples below will be showing only `feature-pack` element.

The example above excludes all the configs, if the goal however is to exclude onyl a specific one, it can be done by providing the identity of the config using `exclude` element. For example, if a configuration was associated with a name but not any model then it would look like this:

[source,xml]
----
<feature-pack location="fp1@maven(org.jboss.universe:community-universe):1#1.0.0.Final">
    <default-configs>
        <exclude name="config1"/>
    </default-configs>
</feature-pack>
----

And if the configuration was associated with a name and a model, both of them will have to be specified, e.g.

[source,xml]
----
<feature-pack location="fp1@maven(org.jboss.universe:community-universe):1#1.0.0.Final">
    <default-configs>
        <exclude name="config1" model="model1"/>
    </default-configs>
</feature-pack>
----

In case there are multiple named configs that are associated with the same model, e.g.

[source,xml]
----
<feature-pack xmlns="urn:jboss:galleon:feature-pack:1.0"
                location="fp1@maven(org.jboss.universe:community-universe):1#1.0.0.Final">

  <config model="model1" name="config1">
    <!-- config body -->
  </config>
  <config model="model1" name="config2">
    <!-- config body -->
  </config>

  <config model="model2" name="config1">
    <!-- config body -->
  </config>
  <config model="model2" name="config2">
    <!-- config body -->
  </config>

</feature-pack>
----

[[excl-configs-by-model]]They can be excluded altogether by specifying the model name, e.g.
[source,xml]
----
<installation xmlns="urn:jboss:galleon:provisioning:1.0">
    <feature-pack location="fp1@maven(org.jboss.universe:community-universe):1#1.0.0.Final">
        <default-configs>
            <exclude model="model1"/>
        </default-configs>
    </feature-pack>
</installation>
----

This installation will include configs `model2:config1` and `model2:config2`.
