### Feature-pack metadata (feature-pack.xml)

Feature-pack metadata contains the following information:

* *GAV* - feature-pack groupId, artifactId and version;

* _(optional)_ *dependencies* -  dependencies on other feature-packs.

* _(optional)_ *config* -  config elements describe the default configurations are generated generated for the installation (there could be more than one configuration);

* _(optional)_ *default packages* - the names of the packages that are installed by default.


Here is an illustration of how it may look like in a *feature-pack.xml* file:

[source,xml]
----
 <feature-pack xmlns="urn:jboss:galleon:feature-pack:1.0"
                groupId="org.my-group"
                artifactId="my-artifact"
                version="1.0.0.Alpha1">
    <dependencies>
        <dependency groupId="org.another-group"
                    artifactId="another-artifact"
                    version="3.0.0.Final"/>
    </dependencies>
    <config>
        <props>
            <prop name="prop1" value="value1"/>
            <prop name="prop2" value="value2"/>
        </props>
        <feature-group name="group1"/>
        <feature spec="feature1">
            <param name="p1" value="v1" />
            <param name="p2" value="v2" />
        </feature>
    </config>
    <default-packages>
        <package name="package1"/>
        <package name="package2"/>
    </default-packages>
 </feature-pack>
----

In this example:

* feature-pack *org.my-group:my-artifact:1.0.0.Alpha1* depends on feature-pack *org.another-group:another-artifact:3.0.0.Final*;

* config element describes the default configuration that will be generated;

* packages *package1* and *package2* are installed by default.

