### Feature-pack metadata (feature-pack.xml)

Generally, feature-pack metadata contains the following information:

* *Feature-pack location* - string expression that indicates how to resolve the feature-pack artifact from a remote repository and how it can be identified among other feature-packs;

* _(optional)_ *dependencies* -  dependencies on other feature-packs.

* _(optional)_ *configuration* -  the default configurations of the product (there could be more than one default configuration);

* _(optional)_ *default packages* - names of the packages that are installed by default.


Here is an illustration of how it may look like in a `feature-pack.xml` file:

[source,xml]
----
<feature-pack xmlns="urn:jboss:galleon:feature-pack:2.0"
    location="wildfly-servlet@maven(org.jboss.universe:community-universe):current#14.0.0.Beta2"> <!--1-->
    <dependencies>
        <dependency location="wildfly-core@maven(org.jboss.universe:community-universe):current#6.0.0.Beta1"/> <!--2-->
    </dependencies>
    <config model="standalone" name="standalone.xml"> <!--3-->
        <feature-group name="standalone"/>
        <feature spec="another-feature">
            <param name="p1" value="v1" />
            <param name="p2" value="v2" />
        </feature>
    </config>
    <config model="domain" name="domain.xml">
        <feature-group name="domain"/>
    </config>
    <config model="host" name="host.xml">
        <feature-group name="host"/>
    </config>
    <default-packages> <!--4-->
        <package name="docs"/>
        <package name="modules.all"/>
    </default-packages>
</feature-pack>
----
<1> Feature-pack location and build info;
<2> Dependency on another feature-pack;
<3> Description of the default `standalone.xml` configuration;
<4> List of packages that should be installed by default.

