#### Explicit package inclusion

A package may be explicitly included into the feature-pack's effective package set. For example, given the following feature-pack definition (`feature-pack.xml`):

[source,xml]
----
 <feature-pack xmlns="urn:jboss:galleon:feature-pack:2.0"
                location="fp1@maven(org.jboss.universe:community-universe:1#1.0.0" >
    <default-packages>
        <package name="p1" />
        <package name="p2" />
    </default-packages>
 </feature-pack>
----

and assuming that

* `p2` has an optional dependency on non-default package `p21`,

* `fp1` also contains non-default package `p3`,

* `p3` has an optional dependency on non-default package `p31`.

The effective package set of `fp1` includes `p1`, `p2` and `p21`.

A user may explicitly add package `p3`, exclude `p2` and still leave `p21` in the effective package set using the following configuration:

[source,xml]
----
 <installation xmlns="urn:jboss:galleon:provisioning:2.0">
     <feature-pack location="fp1@maven(org.jboss.universe:community-universe):1#1.0.0">
         <packages>
             <include name="p3"/>
             <exclude name="p2"/>
             <include name="p21"/>
         </packages>
     </feature-pack>
 </installation>
----

The effective package set now will consist of `p1` (default package), `p21` (explicitly included non-default), `p3` (explicitly included non-default) and `p31` (brought in as a dependency of `p3`).

If, for example, the user wanted to further cut down the effective set to `p21` and `p3`, the configuration would change to

[source,xml]
----
 <installation xmlns="urn:jboss:galleon:provisioning:2.0">
     <feature-pack location="fp1@maven(org.jboss.universe:community-universe):1#1.0.0">
         <packages>
             <exclude name="p1"/>
             <exclude name="p2"/>
             <include name="p21"/>
             <include name="p3"/>
             <exclude name="p31"/>
         </packages>
     </feature-pack>
 </installation>
----
